# Generated by Django 5.2.4 on 2025-08-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
